### PR TITLE
Feat/parallelism

### PR DESCRIPTION
**Pull request by itaipelles**

### CODE REVIEW

**Comment by itaipelles** [comment]
@viliusl 
It looks like a lot of changes but its actually quite minor.
added the -p option to bootstrap, run and exec.
Tell me what you think!
(I only have tomorrow and the day after left before i fly away, so lets try to close this before that?)

**Comment by viliusl** [comment]
@itaipelles crap - I left this one for desert and now there are bunch of conflicts - can you take a look?

**Comment by viliusl** [comment]
@itaipelles seems like I managed, let's see what ci says

**Comment by itaipelles** [comment]
@viliusl seems like it should work, if it doesn't i'll take another look.

**Pull request merged**
